BaseUrl: "http://example.com"
LanguageCode: "en-us"
Title: "Beg"

Params:
  Author: "Shafreeck Sea"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "Your ID."
  Github: "shafreeck"
  ShowRelatedPost: True
  Disqus: "shafreeck"
  SyntaxHighlightTheme: "solarized_dark.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"

